export const ProductItemList = [
  {
    id: 1,
    name: "cactus",
    type: "unisex",
    typeImgUrl: "",
    imgUrl: "",
    size: "SS/20",
    discount: 30,
    color: "black",
    price: 300,
    amount: 1,
  },
  {
    id: 2,
    name: "the code",
    type: "unisex",
    typeImgUrl: "",
    imgUrl: "",
    size: "SS/20",
    discount: 30,
    color: "black",
    price: 240,
    amount: 1,
  },
  {
    id: 3,
    name: "carnera",
    type: "unisex",
    typeImgUrl: "",
    imgUrl: "",
    size: "SS/20",
    discount: 30,
    color: "black",
    price: 240,
    amount: 1,
  },
  {
    id: 4,
    name: "the eye",
    type: "unisex",
    typeImgUrl: "",
    imgUrl: "",
    size: "SS/20",
    discount: 30,
    color: "black",
    price: 240,
    amount: 1,
  },
  {
    id: 5,
    name: "duran",
    type: "unisex",
    typeImgUrl: "",
    imgUrl: "",
    size: "SS/20",
    discount: 30,
    color: "black",
    price: 240,
    amount: 1,
  },
];
