export const ProductItemList = [
  {
    id: "prod-p1",
    name: "cactus",
    type: "unisex",
    typeImgUrl: "",
    imgUrl: "",
    size: "SS/20",
    discount: 30,
    color: "black",
    price: 300,
    amount: 1,
  },
  {
    id: "prod-p2",
    name: "the code",
    type: "unisex",
    typeImgUrl: "",
    imgUrl: "",
    size: "SS/20",
    discount: 30,
    color: "black",
    price: 240,
    amount: 1,
  },
  {
    id: "prod-p3",
    name: "carnera",
    type: "unisex",
    typeImgUrl: "",
    imgUrl: "",
    size: "SS/20",
    discount: 30,
    color: "black",
    price: 240,
    amount: 1,
  },
  {
    id: "prod-p4",
    name: "the eye",
    type: "unisex",
    typeImgUrl: "",
    imgUrl: "",
    size: "SS/20",
    discount: 30,
    color: "black",
    price: 240,
    amount: 1,
  },
  {
    id: "prod-p5",
    name: "duran",
    type: "unisex",
    typeImgUrl: "",
    imgUrl: "",
    size: "SS/20",
    discount: 30,
    color: "black",
    price: 240,
    amount: 1,
  },
];
